require(devtools)
devtools::install_version("rstan", version="2.19.3")
devtools::install_version("zoo", version="1.8.0")
devtools::install_version("bayesplot", version="1.7.2")
devtools::install_version("tidyverse", version="1.3.0")
devtools::install_version("dplyr", version="1.0.0")
devtools::install_version("tidyr", version="1.1.0")
devtools::install_version("EnvStats", version="2.3.1")
devtools::install_version("cowplot", version="1.0.0")
devtools::install_version("ggrepel", version="0.8.2")
devtools::install_version("scales", version="1.1.1")
devtools::install_version("ggplot2", version="3.3.2")
devtools::install_version("optparse", version="1.6.6")
devtools::install_version("slider", version="0.2.1") # This might error out and not be installed, but most of the times can be safely ignored
